# Tells Spring Boot where our PostgreSQL database lives
spring.datasource.url=jdbc:postgresql://localhost:5432/rememberwhen_db
spring.datasource.username=prakrutijain
spring.datasource.password=

# Automatically creates/updates database tables based on our @Entity classes (User, etc.)
spring.jpa.hibernate.ddl-auto=update

# Prints the actual SQL Hibernate runs, in the terminal - helpful for learning/debugging
spring.jpa.show-sql=true

tmdb.api.key=f32b5d33b0ba52659359ac95751a4b4f